name: flake8-test-name-CI
on:
  # All PR
  pull_request:
  # master branch merge
  push:
    branches:
      - master
  # release tags
  create:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+*'

jobs:
  linting:
    # Run pre-commit (https://pre-commit.com/)
    # which runs pre-configured linter & autoformatter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - run: bash .github/workflows/install_ci_python_dep.sh
    - run: pre-commit run -a

  test:
    # Test suite run against recent python versions
    # and against a few combination of MongoDB and pymongo
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9, '3.10', 'pypy3.9']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: install ci dependencies
      run: |
        bash .github/workflows/install_ci_python_dep.sh
    - name: install dep
      run: pip install .
    - name: Run test suite
      run: pytest
    - name: Send coverage to Coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_SERVICE_NAME: github
      if: ${{ matrix.python-version == 3.9 }}
      run: coveralls

  build-n-publish:
    runs-on: ubuntu-latest
    needs: [linting, test]
    if: github.event_name == 'create' && startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: build wheel
      run: |
        pip install wheel
        python setup.py sdist bdist_wheel
    - name: publish pypi
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.pypi_token }}